name: Deploy to Render

on:
  push:
    branches:
      - main # Chạy workflow khi có thay đổi trên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Lấy mã nguồn mới nhất từ GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Phiên bản Node.js bạn đang sử dụng

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build # Nếu ứng dụng của bạn cần build (e.g., React, Next.js)

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # Sử dụng API Key từ GitHub Secrets
        run: |
          curl -X POST "https://api.render.com/deploy" \
          -H "Authorization: Bearer $RENDER_API_KEY"